#ARITHMATIC OPERATOR

#ADDITION TYPE
X=10
Y=20
print(X+Y)
#SUBTRACTION TYPE
X=20
Y=10
print(X-Y)
#DIVISION TYPE
x=12
y=5
print(x/y)
#MULTIPLICATION TYPE
X=573
Y=64
print(X*Y)
#MODULUS TYPE (VAGSHESH DAKHABEY)
X=47
Y=2
print(X%Y)
#EXPONENTIATION TYPE
X=5
Y=2
print(X**Y) # 5 KAY 2 BAR GUN KORBEY Y=3 HOILEY 3 BAR GUN KORBEY 5 KEY
#FOOR DIVISION TYPE
X=15
Y=2
print(X//Y)  #// FLOOR DIVISION AY .5 ASHBEY NA (/ AY DIVISON AY . 5 ASHTO)
