
A=34   #GLOBAL SCOPE KARON AYTA FUNCTION UPOREY ASEY
B=45
C=76
def Shanto():
    global B    # GLOBAL KEYWORD DEAR KARON AY GLOBAL SCOPE AY B ER VALUE LOCAL SCOPE AY CHANGE HOISEY
    B=56        #LOCAL KARON AYTA FUNCTION VITOR AY ASEY
    C=15
    print(B)
    print(A)
    print(C)
Shanto()
print(B)
print(C)     #GLOBAL SCOPE ER OUTPUT DAKHAR JONNO print() FUNCTION ER NICHEY DETE HOBEY
